# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenancy.TenantData'),
        ),
    ]
