# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:15
from __future__ import unicode_literals

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
