# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 22:15
from __future__ import unicode_literals

from django.db import migrations

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=common.fields.TimeZoneField(default='US/Pacific', max_length=32),
        ),
    ]
