# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 21:28
from __future__ import unicode_literals

import django.db.models.deletion
import tenant_schemas.storage
from django.conf import settings
from django.db import migrations, models

import files.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=tenant_schemas.storage.TenantFileSystemStorage(),
                                          upload_to=files.models.get_upload_path, verbose_name='File')),
                ('name', models.CharField(help_text='The original filename', max_length=255, verbose_name='Name')),
                ('mimetype', models.TextField(blank=True, default='', max_length=255)),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Owner')),
            ],
        ),
    ]
