# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:49
from __future__ import unicode_literals

import datetime

import enumfields.fields
import tenant_schemas.storage
from django.db import migrations, models

import files.models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='ttl',
            field=models.DurationField(blank=True, default=datetime.timedelta(7), help_text='How long file with be stored', null=True,
                                       verbose_name='TTL'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploader',
            field=enumfields.fields.EnumField(default='USER', enum=files.models.FileUploader, max_length=32),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=tenant_schemas.storage.TenantFileSystemStorage(
                location='/home/yushkovsky/Dropbox/hcrm/email/bin/media/file-storage'), upload_to=files.models.get_upload_path,
                verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(editable=False, help_text='The original filename', max_length=255, verbose_name='Name'),
        ),
    ]
