# Generated by Django 2.0.2 on 2018-02-28 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import files.models
import tenancy.storage
import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0002_auto_20171112_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=tenancy.storage.TenantFileSystemStorage(base_url='/media/file-storage', location=(
            '/home/yushkovsky/Dropbox/hcrm/email/bin/media', 'file-storage')), upload_to=files.models.get_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='owner',
            field=models.ForeignKey(limit_choices_to=users.utils.tenant_users, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
