# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_contact_contactlist_emailaccount_participation_step_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('port', models.PositiveIntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField(verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='EmailProviderPresets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
