# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0005_auto_20160523_2240'),
        ('campaigns', '0003_basicsettings_emailproviderpresets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='TextStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='EmailProviderPresets',
            new_name='EmailStage',
        ),
        migrations.CreateModel(
            name='CoolMailbox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
        migrations.AddField(
            model_name='step',
            name='emails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.EmailStage'),
        ),
        migrations.AddField(
            model_name='step',
            name='offset',
            field=models.PositiveIntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='mailbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CoolMailbox'),
        ),
        migrations.AddField(
            model_name='step',
            name='sequence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaigns.Sequence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='texts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.TextStage'),
        ),
    ]
