# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20170719_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConnectionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.TextField(blank=True, default=None, help_text='Example: smtp+ssl://myusername:mypassword@someserver <br /><br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).', null=True, verbose_name='URI')),
            ],
        ),
        migrations.DeleteModel(
            name='BasicSettings',
        ),
        migrations.RenameField(
            model_name='emailaccount',
            old_name='mailbox',
            new_name='incoming',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='outgoing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campaigns.SmtpConnectionSettings'),
            preserve_default=False,
        ),
    ]
