# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0005_auto_20170724_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='outgoing',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoolMailbox',
        ),
        migrations.DeleteModel(
            name='EMailAccount',
        ),
        migrations.DeleteModel(
            name='SmtpConnectionSettings',
        ),
    ]
