# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 18:46
from __future__ import unicode_literals

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0010_auto_20170813_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sex',
        ),
        migrations.AddField(
            model_name='contact',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
