# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0006_auto_20170814_0723'),
        ('campaigns', '0014_auto_20170828_2139'),
    ]

    operations = [
    ]
