# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0001_initial'),
        ('campaigns', '0013_auto_20170824_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='participation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
