# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 22:38
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
from django.db import migrations, models

import campaigns.models
import common.fields
import tenancy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20170901_1736'),
        ('post_office', '0006_attachment_mimetype'),
        ('contacts', '0003_auto_20170906_2014'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=tenancy.storage.PrivateMediaRootTenancyS3BotoStorage(),
                                          upload_to=campaigns.models.get_upload_path, verbose_name='File')),
                ('name', models.CharField(help_text='The original filename', max_length=255, verbose_name='Name')),
                ('mimetype', models.TextField(blank=True, default='', max_length=255)),
                ('emails', models.ManyToManyField(related_name='attachments', to='campaigns.EmailStage', verbose_name='Email stages')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.EmailAccount'),
        ),
        migrations.AddField(
            model_name='emailstage',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.EmailAccount'),
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='post_office.Email')),
                ('stage',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='campaigns.EmailStage')),
                ('contact',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='contacts.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=enumfields.fields.EnumField(default='DRAFT', enum=campaigns.models.CampaignStatus, max_length=32),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailstage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.EmailAccount'),
        ),
        migrations.AlterField(
            model_name='step',
            name='weekdays',
            field=common.fields.EnumSetField(blank=True, default=[campaigns.models.Weekdays('SUN'), campaigns.models.Weekdays('MON'),
                                                                  campaigns.models.Weekdays('TUE'), campaigns.models.Weekdays('WED'),
                                                                  campaigns.models.Weekdays('THU'), campaigns.models.Weekdays('FRI'),
                                                                  campaigns.models.Weekdays('SAT')], enum=campaigns.models.Weekdays),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('contact', 'campaign')]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.Participation', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='emailstage',
            name='sender_name',
            field=models.TextField(blank=True),
        ),
    ]
