# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 23:13
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import campaigns.models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0018_auto_20171021_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_max_number', models.PositiveIntegerField(default=100, help_text='Max number of step emails per day',
                                                                validators=[django.core.validators.MinValueValidator(1),
                                                                            django.core.validators.MaxValueValidator(200)])),
                ('email_send_delay', models.PositiveIntegerField(default=10, help_text='Delay between each email send (seconds)')),
                ('track_opening', models.BooleanField(default=True)),
                ('track_links', models.BooleanField(default=True)),
                ('personalize_to_filed', models.BooleanField(default=False,
                                                             help_text="Include the contact's name in the recipients field to make it more personalized ")),
                ('campaign',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='campaigns.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=enumfields.fields.EnumField(default='ACTIVE', enum=campaigns.models.ParticipationStatus, max_length=32),
        ),
    ]
