# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0019_auto_20171024_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedStageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Participation')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Step')),
            ],
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='track_links',
            field=models.BooleanField(default=True, help_text='Enables/disables links clicks tracking'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='track_opening',
            field=models.BooleanField(default=True, help_text='Enables/disables emails opens tracking'),
        ),
        migrations.AddField(
            model_name='participation',
            name='passed_steps',
            field=models.ManyToManyField(related_name='participations', through='campaigns.PassedStageResult', to='campaigns.Step'),
        ),
    ]
