# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 00:11
from __future__ import unicode_literals

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0021_auto_20171105_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='offset',
        ),
        migrations.AddField(
            model_name='step',
            name='offset',
            field=models.DurationField(default=datetime.timedelta(1),
                                       validators=[django.core.validators.MinValueValidator(datetime.timedelta(0, 900))]),
        ),
    ]
