# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0022_auto_20171106_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='stop_sending_on_reply',
            field=models.BooleanField(default=True, help_text='Stop contact participation in campaign on reply'),
        ),
    ]
