# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 00:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import campaigns.models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0024_auto_20171118_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', enumfields.fields.EnumField(enum=campaigns.models.TrackingType, max_length=32)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Meta')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.ScheduledEmail')),
            ],
        ),
    ]
