# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 09:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0026_auto_20171128_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='inbox_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled',
                                       to='django_mailbox.Message'),
        ),
    ]
