# Generated by Django 2.0.4 on 2018-04-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0006_auto_20180319_1859'),
        ('post_office', '0006_attachment_mimetype'),
        ('campaigns', '0028_auto_20180228_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinginfo',
            name='email',
        ),
        migrations.AddField(
            model_name='trackinginfo',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked', to='django_mailbox.Message'),
            preserve_default=False,
        ),
    ]
