# Generated by Django 2.0.6 on 2018-06-15 20:02

import datetime

import django.db.models.deletion
import enumfields.fields
import phonenumber_field.modelfields
from django.db import migrations, models

import campaigns.models
import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0029_auto_20180404_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True, verbose_name='city')),
                ('state', models.TextField(blank=True, verbose_name='state')),
                ('country', models.TextField(blank=True, verbose_name='country')),
                ('street_address', models.TextField(blank=True, verbose_name='street address')),
                ('zip_code', models.TextField(blank=True, verbose_name='zip code')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('first_name', models.TextField(blank=True, verbose_name='first name')),
                ('last_name', models.TextField(blank=True, verbose_name='last name')),
                ('title', models.TextField(blank=True)),
                ('timezone', common.fields.TimeZoneField(blank=True, max_length=32)),
                ('company_name', models.TextField(blank=True)),
                ('company_employee_count', enumfields.fields.EnumField(enum=campaigns.models.CompanyEmployeeCountLevel, max_length=32)),
                ('company_revenue', enumfields.fields.EnumField(enum=campaigns.models.CompanyRevenue, max_length=32)),
                ('department', enumfields.fields.EnumField(enum=campaigns.models.LeadDepartment, max_length=32)),
                ('level', enumfields.fields.EnumField(enum=campaigns.models.LeadLevel, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadGenerationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True)),
                ('company_industry_name', models.TextField(blank=True, null=True)),
                ('company_sic_code', models.IntegerField(blank=True, null=True)),
                ('company_employee_count',
                 common.fields.EnumSetField(default=[], enum=campaigns.models.CompanyEmployeeCountLevel, form_size=None)),
                ('company_revenue', common.fields.EnumSetField(default=[], enum=campaigns.models.CompanyRevenue, form_size=None)),
                ('name', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('department', common.fields.EnumSetField(default=[], enum=campaigns.models.LeadDepartment, form_size=None)),
                ('level', common.fields.EnumSetField(default=[], enum=campaigns.models.LeadLevel, form_size=None)),
                ('email_deliverability',
                 enumfields.fields.EnumField(default='ANY', enum=campaigns.models.LeadEmailDeliverability, max_length=32)),
                ('city', models.TextField(blank=True, verbose_name='city')),
                ('state', models.TextField(blank=True, verbose_name='state')),
                ('country', models.TextField(blank=True, verbose_name='country')),
                ('zip_code', models.TextField(blank=True, verbose_name='zip code')),
                (
                    'status',
                    enumfields.fields.EnumField(default='CREATED', enum=campaigns.models.LeadGenerationRequestStatus, max_length=32)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('import_per_day', models.PositiveIntegerField(default=100)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaignsettings',
            name='email_send_delay',
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='email_send_delay',
            field=models.DurationField(default=datetime.timedelta(0, 10), help_text='Delay between each email send (seconds)'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads',
                                    to='campaigns.LeadGenerationRequest'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='status',
            field=enumfields.fields.EnumField(default='CREATED', enum=campaigns.models.ContactLeadStatus, max_length=32),
        ),
    ]
