# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0002_auto_20170905_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='lists', to='contacts.Contact'),
        ),
    ]
